// user module mutation-types
const SET_LOGIN_FORM_MODAL_VISIBLE = 'SET_LOGIN_FORM_MODAL_VISIBLE'
const SET_MY_INFO = 'SET_MY_INFO'
const REMOVE_MY_INFO = 'REMOVE_MY_INFO'
const UPDATE_NICKNAME = 'UPDATE_NICKNAME'

// weather module mutation-types
const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'
const SET_CURRENT_WEATHER_DATA = 'SET_CURRENT_WEATHER_DATA'
const SET_ONE_CALL_API_DATA = 'SET_ONE_CALL_API_DATA'
const SET_CURRENT_COORDS = 'SET_CURRENT_COORDS'
const SET_SEARCH_COORDS = 'SET_SEARCH_COORDS'
const SET_FORECAST_HOURLY_DAY_TYPE = 'SET_FORECAST_HOURLY_DAY_TYPE'
const SET_FORECAST_HOURLY_INFO = 'SET_FORECAST_HOURLY_INFO'
const SET_FORECAST_DAILY_INFO = 'SET_FORECAST_DAILY_INFO'

// alert module mutation-types
const SET_USER_API_RESPONSE = 'SET_USER_API_RESPONSE'
const RESET_USER_API_RESPONSE = 'RESET_USER_API_RESPONSE'
const SET_WEATHER_API_RESPONSE = 'SET_WEATHER_API_RESPONSE'
const RESET_WEATHER_API_RESPONSE = 'RESET_WEATHER_API_RESPONSE'

export {
  SET_LOGIN_FORM_MODAL_VISIBLE,
  SET_MY_INFO,
  REMOVE_MY_INFO,
  UPDATE_NICKNAME,

  SET_CURRENT_WEATHER_DATA,
  SET_ONE_CALL_API_DATA,
  SET_CURRENT_LOCATION,
  SET_CURRENT_COORDS,
  SET_SEARCH_COORDS,
  SET_FORECAST_HOURLY_DAY_TYPE,
  SET_FORECAST_HOURLY_INFO,
  SET_FORECAST_DAILY_INFO,

  SET_USER_API_RESPONSE,
  RESET_USER_API_RESPONSE,
  SET_WEATHER_API_RESPONSE,
  RESET_WEATHER_API_RESPONSE,
}
