const FORECAST_ALL_PC_SHEET_HEIGHT = '85vh'
const FORECAST_ALL_MOBILE_SHEET_HEIGHT = '50%'
const FORECAST_ALL_PC_SHEET_PADDING = 'mx-16'
const FORECAST_ALL_MOBILE_SHEET_PADDING = 'mx-0'
const FORECAST_DIAGONOSE_PC_SHEET_HEIGHT = '100vh'
const FORECAST_DIAGONOSE_MOBILE_SHEET_HEIGHT = '50%'
const PC_TITLE_SIZE = 'text-h4 font-weight-bold'
const MOBILE_TITLE_SIZE = 'text-h6'
const PC_TABLE_TD_FONT_SIZE = 'text-h6'
const MOBILE_TABLE_TD_FONT_SIZE = 'body-2'

export {
  FORECAST_ALL_PC_SHEET_HEIGHT,
  FORECAST_ALL_MOBILE_SHEET_HEIGHT,
  FORECAST_ALL_PC_SHEET_PADDING,
  FORECAST_ALL_MOBILE_SHEET_PADDING,
  FORECAST_DIAGONOSE_PC_SHEET_HEIGHT,
  FORECAST_DIAGONOSE_MOBILE_SHEET_HEIGHT,
  PC_TITLE_SIZE,
  MOBILE_TITLE_SIZE,
  PC_TABLE_TD_FONT_SIZE,
  MOBILE_TABLE_TD_FONT_SIZE,
}
