const TEMPERATURE_INDEX = 0
const RAIN_INDEX = 1
const WIND_INDEX = 2

const RED = '#f72047'
const YELLOW = '#ffd200'
const GREEN = '#1feaea'
const BLUE = '#42b3f4'

const PC_HEIGHT = '80vh'
const MOBILE_HEIGHT = '50%'
const PC_PADDING = 'pa-10'
const MOBILE_PADDING = 'pa-4'

const CELSIUS_UNIT = '°C'
const DAYJS_DATE_AND_DAY_FORMAT = 'MM/DD(dddd)'
const FULL_DATE_WITH_DAY_FORMAT = 'YYYY.MM.DD(dddd)'
const FULL_DATE_ONLY_FORMAT = 'YYYY.MM.DD'
const ONE_HOUR = '1h'
const TIME_FORMAT = 'A hh'
const SHORT_DATE_WITH_DAY_FORMAT = 'DD(dd)'
const SHORT_DATE_ONLY_FORMAT = 'DD'

export {
  TEMPERATURE_INDEX,
  RAIN_INDEX,
  WIND_INDEX,

  RED,
  YELLOW,
  GREEN,
  BLUE,

  PC_HEIGHT,
  MOBILE_HEIGHT,
  PC_PADDING,
  MOBILE_PADDING,

  CELSIUS_UNIT,
  DAYJS_DATE_AND_DAY_FORMAT,
  FULL_DATE_WITH_DAY_FORMAT,
  FULL_DATE_ONLY_FORMAT,
  ONE_HOUR,
  TIME_FORMAT,
  SHORT_DATE_WITH_DAY_FORMAT,
  SHORT_DATE_ONLY_FORMAT,
}
